vich_uploader:
    db_driver: orm

    mappings:
       artists:
           uri_prefix: /images/artists
           upload_destination: '%kernel.project_dir%/public/images/artists'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer